<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <BaseOutputPath>\output\Proton\QuickTemplate</BaseOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Proton" Version="1.0.10" />
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest"/>
		<None Include="..\Proton\wwwroot\proton.js" Link="wwwroot\static\lib\proton\proton.js" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
      
    </ItemGroup>

</Project>